### ISSUE TITLE
Issue with headers in the examples

### ISSUE THREAD

**Issue by jpava001** [TinkoffCreditSystems/gatling-amqp-plugin#1]
Hello,

When I try to run the tests in either of the examples, I get the following error

[error]  found   : String("testvalue")
[error]  required: io.gatling.commons.validation.Validation[Map[String,String]]
[error]         .headers(Map("testheader" -> "testvalue"))

Can you please assist?

Thanks,

Jairo

**Comment by jpava001** [comment]
I was able to fix by updating the line

`.headers(Map("testheader" -> "testvalue"))`

to 

`.headers(Map("testheader" -> "testvalue").expressionSuccess)`

But should this be necessary?

**Comment by red-bashmak** [comment]
Hello, Jairo.

Yes i's necessary append `.expressionSuccess`

It is strange that implicit conversion does not work in `.headers(Map("testheader" -> "testvalue"))`.
I mean this [ValidationImplicits.scala#L64](https://github.com/gatling/gatling/blob/8e531308718a2f8f90168a72c1091372b2b4a373/gatling-core/src/main/scala/io/gatling/core/ValidationImplicits.scala#L64).
I thought, it should have added `.expressionSuccess` to any type and also to Map[String,String].

**Comment by red-bashmak** [comment]
You may replace `.headers(Map("testheader" -> "testvalue"))` with `.property("testheader", "testvalue")`, if you need to pass one header

**Comment by jpava001** [comment]
Thank you.
