### ISSUE TITLE
Known issues for requestReply?

### ISSUE THREAD

**Issue by ehmkah** [TinkoffCreditSystems/gatling-amqp-plugin#15]
I use this plugin for requestReply. Publishing for messages works but not all received messages are detected correctly.

I use the `matchByMessage` and have an implementation which extracts the id of the sent and received message. I looks like that message is called with each message but at the end of the test there are always more or less active messages. Are there any known issues that messages are received to early before they are tracked as sent? 

```
[####################################################################------] 93%
          waiting: 0      / active: 7      / done: 93    
================================================================================
```

**Comment by red-bashmak** [comment]
You made sure that the queue was empty before test. Possibly messages from old runs were in queue, and they successfully matched.

**Comment by red-bashmak** [comment]
It was be good if you attach source code of your scenario

**Comment by ehmkah** [comment]
Thanks for your fast reply. Yes the queue is empty - Example can be a little bit difficult, because it is our real-system. Maybe I am able to make a small sample out of it. 

At the moment it looks like that a) messages are sent correctly (very good), b) maybe messages are changed during receiving OR  we found a bug in one of our services (hooray)

**Comment by ehmkah** [comment]
Ok seems that we mess up something in our services. I am closing the ticket right now.
