### ISSUE TITLE
Request/Reply Message Matching using headers

### ISSUE THREAD

**Issue by drewvella-dpg** [TinkoffCreditSystems/gatling-amqp-plugin#16]
Hey Guys,

I'm relatively new to scala/gatling and I'm working on a test where I want to match messages on different queues using a custom headers . From what I've gathered I would need to use the mapByMessage but unfortunately have been unable to find an example on how to do this. Does anyone have an example?

**Comment by ehmkah** [comment]
I made a MR with an example how you could do it. I hope it will be merged and more important helps :-)

**Comment by drewvella-dpg** [comment]
Thanks for that! Can you elaborate a bit to make sure I understood correctly?

```  
  // method is called:
    // - for each message which will be sent out
    // - for each message which has been received
```

Would I need to code the logic to extract the value from the headers and return that value for it to match or also code the part to teach it how to match? ie:

Scenario 1:
Request sent  on queue 1 - Matcher kicks in and extracts value from header
Response comes in on queue 2 - Matcher kicks in and extracts value from header plugin automatically matches

Scenario 2:
Request sent  on queue 1 - Matcher kicks in and extracts value from header and store the value to correlate it later
Response comes in on queue 2 - Matcher kicks in and extracts value from header custom logic to correlate with list

**Comment by ehmkah** [comment]
In my opinion scenario 1 is correct. Your method calculates the values from messages and the plugin does the rest. You do not have to store the values somewhere. 

Attention: If for some reason the method returns the same ID for two different sent-messages and gatling is waiting for the response of those two messages it happens that one message-mapping is not detected. (To see it return always "1" - its diffuclt to explain)

Maybe a small testsetup which starts a rabbitmq container and runs out of the box would be a good benefit.

**Comment by drewvella-dpg** [comment]
Ok I think I understood what needs to be done! Cheers!
