### ISSUE TITLE
Support for gatling 3.5?

### ISSUE THREAD

**Issue by ehmkah** [TinkoffCreditSystems/gatling-amqp-plugin#23]
Gatling 3.5.0 has been (https://gatling.io/2020/12/18/gatling-3-5-0-and-gatling-frontline-1-13-0-are-out/) released. Itnow runs wih scala 2.13. Are there plans when to support this version of gatling?

**Comment by jigarkhwar** [comment]
yeah, sure. Q1 Planned

**Comment by red-bashmak** [comment]
@ehmkah, new version 0.5.0 with support gatling 3.5.1 and scala 2.13 is released.
