### ISSUE TITLE
Can you help me with AMQPS?

### ISSUE THREAD

**Issue by decado87** [TinkoffCreditSystems/gatling-amqp-plugin#6]
Hellou,
Im new in Gatling and Scala at all. Can you please show me how to create connectionFactory to AMQPS?
Now I got error Connection reset
Many thanks

my code:
`val amqpConf: AmqpProtocolBuilder = amqp
    .connectionFactory(
      rabbitmq
        .host("mq.xxx.xxx.com")
        .port(5671)
        .vhost("/")
        .username("someUsername")
        .password("somePassword")
    )
    .usePersistentDeliveryMode`

**Comment by red-bashmak** [comment]
Hello,
I think you need to check that your amqp server is up and running. In your code I not seeing explicit errors

**Comment by seanyu4296** [comment]
i have faced the same problem what i ended up doing is @decado87 

```scala
  val cf = new ConnectionFactory()
  cf.setUri("amqps://username:password@yourrabbitmq.com")
  val amqpConf: AmqpProtocolBuilder = amqp
    .connectionFactory(cf)
 ```
