### ISSUE TITLE
How to cross check the message id in request and reply using check block

### ISSUE THREAD

**Issue by akhilev** [TinkoffCreditSystems/gatling-amqp-plugin#7]
i tried the  example provided (RequestReply)
But here it is not acknowledge the message response(hence failing the test), even though i can see all the messages are being consumed from the queue ( rep-queue-mq) by the test suite.
I am not sure what i am missing here, may be some additional check block.i think i miss some kind of comparison or protocol configuration here ( i tried to figure out whether id exists in response with  jsonPath("$.id").exists, but its failing in runtime due to  

type mismatch;
 found   : io.gatling.core.check.CheckBuilder[io.gatling.core.check.jsonpath.JsonPathCheckType,com.fasterxml.jackson.databind.JsonNode,String]
 required: ru.tinkoff.gatling.amqp.AmqpCheck
    (which expands to)  io.gatling.core.check.Check[ru.tinkoff.gatling.amqp.request.AmqpProtocolMessage]
          bodyString.exists,jsonPath("$.id").exists)

I am fairly new to scala and gatling, so i am not exactly sure of what is causing the issue( seems the plugin is expecting some other type expression: check(bodyString.exists,jsonPath("$.id").exists)).

class RequestReply extends Simulation{

  val amqpConf: AmqpProtocolBuilder = amqp
    .connectionFactory(
      rabbitmq
        .host("localhost")
        .port(9081)
        .username("usr")
        .password("pwd")
        .vhost("/vhost")
    )
    .replyTimeout(60000)
    .consumerThreadsCount(8)
    .matchByMessageId
    .usePersistentDeliveryMode

  val scn: ScenarioBuilder = scenario("AMQP")
    .feed(idFeeder) /
    .exec(
      amqp("Consume Publish Test").requestReply
        .directExchange("direct.exchange", "direcs.rk")
        .replyExchange("rep-queue-mq") // here i given the queue name where the message is published by the application after processing (this queue is another exchange)
        .textMessage("{\"id\":\"${id}\",\"message\":\"testmessage\"}")
        .messageId("${id}")
        .priority(0)
        .property("content_type", "application/json")
        .check(
          bodyString.exists)

Note : I tried to publish and consume from the same queue ..its working there.( tried to print the response in this case and found the below output as expected.

Response body: 
{"id":"10020","msg":"test"}
Response body: 
{"id":"10021","msg":"test"}
Response body: 
{"id":"10022","msg":"test"}

.check(
        bodyString.exists,bodyString.saveAs("BODY"))
  ).exec({session =>
  val response = session("BODY").as[String]
  println(s"Response body: \n$response")
  session
})

**Comment by red-bashmak** [comment]
I hope your problems is already solved. 
But i think the reason of "type mismatch;"  is that you havn't ` import ru.tinkoff.gatling.amqp.Predef._`.
Second - you no need manualy check id's of message, if you write`.matchByMessageId` it work under hood in plugin. Id checking is base of request/response matching algorithm
