### ISSUE TITLE
Any option to add Topic support for exchange?

### ISSUE THREAD

**Issue by gutylin78** [TinkoffCreditSystems/gatling-amqp-plugin#8]
Hello, Is there any option to add Topic support in your AMQP library?
I'd need to use both, topic and direct but I'm jjust realized that your lib does not have support for Topic :(.
Thx.

**Comment by ehmkah** [comment]
I also needed this feature. So I first upgraded this plugin to work with gatlin 3.4 and then added topic support. You can find my changes in https://github.com/TinkoffCreditSystems/gatling-amqp-plugin/pull/14

Hope this helps

**Comment by ehmkah** [comment]
@gutylin78  - your feature request has been merged to master. Could you check whether its working for you?

**Comment by drewvella-dpg** [comment]
I just tested this myself and it works perfectly! Any chance we can publish the version?

**Comment by red-bashmak** [comment]
I release v0.0.4 with topics support

**Comment by ehmkah** [comment]
@drewvella-dpg -- could you please close this issue, as it has been fixed? Thank you.

**Comment by red-bashmak** [comment]
topic support in  #14
